stages:
  data_ingestion:
    cmd: python .\src\data\data_ingestion.py
    deps:
    - .\src\data\data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python .\src\data\data_preprocessing.py
    deps:
    - .\src\data\data_preprocessing.py
    - data/raw
    outs:
    - data/processed
  feature_engineering:
    cmd: python .\src\features\feature_engineering.py
    deps:
    - .\src\features\feature_engineering.py
    - data/processed
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python .\src\models\model_building.py
    deps:
    - .\src\models\model_building.py
    - data/features
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python .\src\visualization\model_evaluation.py
    deps:
    - .\src\visualization\model_evaluation.py
    - models/model.pkl
    metrics:
    - metrics.json
